### ISSUE TITLE
Wordpress 4.3 Compatibility Issue

### ISSUE THREAD

**Issue by jtrag** [gndev/shortcodes-ultimate#21]
Since updating to Wordpress 4.3, Shortcodes Ultimate is causing the following error:

Warning: require_once(inc/vendor/sunrise.php): failed to open stream: No such file or directory in /public_html/wp-content/plugins/shortcodes-ultimate-master/shortcodes-ultimate.php on line 20

Fatal error: require_once(): Failed opening required 'inc/vendor/sunrise.php' (include_path='') in /public_html/wp-content/plugins/shortcodes-ultimate-master/shortcodes-ultimate.php on line 20

Does anyone know if there is there a temp fix/workaround for this until the plugin is updated?

**Comment by gndev** [comment]
Hi,

did you tried to install plugin from wordpress.org repository?

**Comment by jtrag** [comment]
BTW, the file "inc/vendor/sunrise.php" is where it's supposed to be in the plugin folder, and has the proper permissions/ownership.  So I'm sure that's not the issue.

**Comment by jtrag** [comment]
Yes, I tried installing from Wordpress.org, and even completely removed all of the plugin files/folders and reinstalled manually by downloading from the plugin homepage, and even github clone.

Still getting same error randomly, when navigating the site/wp-admin area.

**Comment by gndev** [comment]
Also, plugin directory should be named 'shortcodes-ultimate', not 'shortcodes-ultimate-master'.

**Comment by jtrag** [comment]
I did try changing the folder name back to shortcodes-ultimate, and it didn't make a difference.

**Comment by jtrag** [comment]
It was working great up until I updated the site to Wordpress 4.3...

**Comment by jtrag** [comment]
Thanks in advance for any/all assistance with this!  I really appreciate it!  :+1:

**Comment by jtrag** [comment]
I just deleted the plugin via wp-admin and completely removed the plugin and reinstalled from Wordpress.org via wp-admin, and it's still causing a fatal error.  This time, it wouldn't even activate the plugin due to fatal error.

**Comment by jtrag** [comment]
I'm not 100% sure yet, but I may have figured out a temp fix for it for now.  

It seems that since updating to Wordpress 4.3, Shortcodes Ultimate's scripts are using more memory than the php.ini was set to allow.  

I had the server set to allow 1024M already, and just changed it to 2047M and it seems to have stopped the error for now.  

So far so good.  I will keep you posted.  Perhaps you could look into why it might be using more memory after updating to Wordpress 4.3?...

**Comment by jtrag** [comment]
I've been using the site heavily, and after setting php memory limit to 2047M, the error has not occurred again.  Having to set the memory limit to 2047M in php.ini is a bit extreme, but luckily the site is on a VPS of it's own, and has 5+ gigs of RAM allocated to it.

**Comment by legion1978** [comment]
2047M ---theres got to be something else going on, mate.

**Comment by jtrag** [comment]
It very well may be, but the error only occurred with the Shortcodes Ultimate plugin activated...

On the site, I'm using the SU tables, and Buttons heavily.  Not sure if that helps or not?...

**Comment by legion1978** [comment]
well i did have some word before about SU and memory issues but never bumped into one (afaik). i try to reduce shortcodes to the minimum, specially regarding aesthetics, so i sometimes copy them classes to apply them manually and use the elements provided by the theme, and use SU only for specific things. works fine atm :)

**Comment by jtrag** [comment]
I was thinking of copying & pasting the classes into my theme's custom css, and implementing them manually...  but at this point, it would probably be a LOT of work for me :-| 

It's okay.  I will just keep the memory limit at 2047M.  Perhaps you should look into a way to make SU even more efficient, since not everyone that may run into the issue, will have the ability to change/override the php.ini settings to increase the memory limit.

BTW...  Thank you guys for your replies/time.  I appreciate it :+1:
