### ISSUE TITLE
box border radius leaves small area of white pixels in corner

### ISSUE THREAD

**Issue by Sophist-UK** [gndev/shortcodes-ultimate#24]
I have a box with dark brown borders with default radius (3px) and default css width (2px), and a title with a brown background. But I see a small area of white pixels between the top corners of the background and the border.

The title-bar corner radius is calculated as a fixed 1px less than the box corner radius, but I believe that it should be the box radius less the border width.

I will see if I can code a PR to:

a. Move the box border width from CSS to parameter; and
b. Fix the calculation

**Comment by gndev** [comment]
Fixed in 5.0.2
