### ISSUE TITLE
Youtube non-ssl

### ISSUE THREAD

**Issue by ChristianVermeulen** [gndev/shortcodes-ultimate#38]
## Description

My site runs on HTTPS, but the plugin automatically creates the youtube embed iframe with HTTP.
Even if I paste the entire video URL including HTTPS it seems to strip the video ID and build uit the embed url with HTTP.

This results in de video not being loaded.
## Reproduce

Insert shortcode: `[su_youtube url="https://www.youtube.com/watch?v=8mcfeLK5YNs" width="1600"]`

![screenshot 2016-06-07 09 21 55](https://cloud.githubusercontent.com/assets/1062751/15849154/69835806-2c91-11e6-8f84-1ae673306aba.png)
## Possible solution

Use HTTPS by default since including HTTPS on HTTP websites poses no problem at all.

**Comment by shakyboum** [comment]
didn't work for me !!

**Comment by negrusti** [comment]
works for me, how come this fix is not in the latest release? This is a show-stopper for HTTPS sites

**Comment by Hube2** [comment]
Can't we just remove the protocol, for example "//www.youtube.com/watch?v=8mcfeLK5YNs"
