### ISSUE TITLE
Nested shortcodes (again)

### ISSUE THREAD

**Issue by premmels** [gndev/shortcodes-ultimate#44]
Hi there,
I want to create a box within a box by using:

[su_box title="Title1"]
  [su_box title="Title2"]
    Box content
  [/su_box]
[/su_box]

where line 4 closes the outer box, not the inner one.

By a suggestion I tried:
[su_box title="Title1"]
  [_su_box title="Title2"]
    Box content
  [_/su_box]
[/su_box]

which doesn't work either and instead shows
"[_su_box title=“Title2″] Box content
[/su_box]"
as the content of the outer box.

This is my minimal problem, I in fact want to create 
an outer box which has
  a row which has
     two columns that each have
          one box

Any suggestions?
Thanks,
Patrick

**Comment by lomboboo** [comment]
confirming. have the same issue

**Comment by tazziedave** [comment]
This is similar to an issue I had with nested accordions, a quick test and the same fix appears to work-

```
[su_box title="Title1"]
[su_box title="Title2"]
Box content
[_/su_box]
[/su_box]
```
Note that the prefix hyphen is used on the inner closing tag, not the opening tag!
