### ISSUE TITLE
Is the plugin dead?

### ISSUE THREAD

**Issue by Hube2** [gndev/shortcodes-ultimate#48]
Vladimir,

Before I start I would like to say: I know how much work supporting a popular plugin can be. Constantly keeping up with vendor scripts that you use, constantly keeping up with changes in WP, making updates when things break. I especially understand this when it comes to a free plugin. People expect a lot more than they are willing to pay for and expect even more when they're getting something for nothing in the first place. The main reason that I purchased your addons was in order to help give you incentive to continue your work.

The main reason that I'm asking is that I was digging around and noticed an update to this plugin on wordpress.org where you changed the "Tested up to" line in the readme.txt file there to "5" and I find this highly suspicious. It could be that you knew you were going to be away for an extended period of time or that you just don't want to be bothered. Unfortunately I will never know which if you either can't answer or decide to ignore this request.

Do you have any plans on correcting the issues that have been developing in this plugin, keeping the scripts updated and keeping up with changes in WP or should I look for a solution to switch to for future projects?

If you're not going to continue to support this project at all, I'll be disappointed, but I'll understand.

I'm not looking for any reasons or explanations, I would just like a simple straight answer.

If you don't want to answer here feel free to reply by email to: hube02 AT earthlink DOT net

Thanks,

~JH

**Comment by gndev** [comment]
Hello John,

the plugin is not dead.

In the near future I plan to fix all minor issues. I’ve been working on a new documentation (docs.getshortcodes.com) and new project site (getshortcodes.com - not launched yet) recently.

Thanks for your support and patience.

**Comment by Hube2** [comment]
Just want to say thanks for replying and that I'm glad that you plan on continuing, and glad that you are still aroung. I was a bit worried I'd need to find or build something new. 

Honestly, your interface for adding shortcodes is the best. Franky, if you removed all of the existing shortcodes from the package and just left the interface and I needed to code my own shortcodes I'd still use it. Sortcodes and the code that goes with them on the front end of the site is easy. A UI that will add shorcodes to tinyMCE is out of my comfort zone.
