### ISSUE TITLE
su_user not working - Fix provided

### ISSUE THREAD

**Issue by TonyGravagno** [gndev/shortcodes-ultimate#56]
I'm using 4.10.1 with PHP7. I'm not getting any su_users output at all:

**\inc\core\shortcodes.php function user** isn't retrieving data from the WP_User. Here's the fix at line 1436:

```
//$user = ( $user && isset( $user->data->$atts['field'] ) ) ? $user->data->$atts['field'] : $atts['default']; // TG Replace with line below
$user = ( $user && $user->__isset( $atts['field'] ) ) ? $user->__get( $atts['field'] ) : $atts['default'];
// Apply custom filter
```

Note also that last comment has a single character typo, corrected here.

I'd submit a pull request but I understand a lot of other changes are being made, and there are 5 pull requests that have already not been merged. This is just one line to fix a core feature. I hope it can get fast-tracked into public updates. That said, I have no idea if this change will work correctly in various versions of WP or PHP. It should be tested...  HTH

Thanks again for an awesome plugin.

**Comment by gndev** [comment]
Hello Tony,

just tested the following shortcodes on PHP 7.0.3 and 7.1.4:

```
[su_user field="user_login"] - current user
[su_user field="user_login" user_id="2"] - specific user
```
They are work as expected.

**Comment by TonyGravagno** [comment]
I was guessing this was going to be tougher than a slam-dunk bug fix. :(
Please leave this open as an FYI to others. If their code works, great. If not then I hope we see more reports on this and that we figure out the pattern. The issue seems simple: Under "some condition" the reference to $user->data is not returning fields, where user->__get() is working. I'll do some research and report back.

Thanks!

**Comment by TonyGravagno** [comment]
I believe I've found the issue. See this [note on PHP migration from v5 to 7](http://docs.php.net/manual/en/migration70.incompatible.php#migration70.incompatible.variable-handling.indirect).

> Old and new evaluation of indirect expressions

Expression | PHP 5 interpretation | PHP 7 interpretation
------------ | ------------- | -------------------
$foo->$bar['baz'] | $foo->{$bar['baz']} | ($foo->$bar)['baz']

The code that's in the `user` method is `$user->data->$atts['field'] `, and we see above how v5 interprets that differently from v7.

To fix this, I modified that construct (two places in one line) to include braces around the array references:
`$user->data->{$atts['field']}`

I can't explain why you're not seeing what I am. I'm guessing you have a PHP5 directive in a config file.

**Comment by gndev** [comment]
I've created new branch user_field_php7 with fix. Could you checkout it and test the new code?

**Comment by gndev** [comment]
Just removed that branch and merged pull request with fix. Everything works fine on 5.2.4, 5.2.17, 5.3.29, 5.4.45, 5.5.38, 5.6.20, 7.0.3 and 7.1.4 :)

**Comment by TonyGravagno** [comment]
Yup, looks like it's working in 7.0.14. Closing with gratitude and appreciation!
