### ISSUE TITLE
Carousel images don't scale

### ISSUE THREAD

**Issue by TonyGravagno** [gndev/shortcodes-ultimate#58]
I have several images of different sizes that I'd like to see in a su_carousel. I was hoping the container would be limited to the width and height, with each image scaled within that container to preserve all the content. Unfortunately each image is cropped within the display area.

I haven't looked at the code yet but will do so as time permits. Does anyone have tips for handling this situation? Thanks.

**Comment by gndev** [comment]
Hello Tony,

don't waste your time to that code. Slider and carousel will be rewritten in closest versions. Swiper will be replaced with owlCarousel.

**Comment by TonyGravagno** [comment]
Got it. Thanks bud!
