### ISSUE TITLE
Trivial typos

### ISSUE THREAD

**Issue by TonyGravagno** [gndev/shortcodes-ultimate#59]
1. On the Settings>About page: "How does it works"
    Should either be "How does it work" or "How it works".
1. Actual Settings page: "Please keep in mind: this option **is not affects** your already inserted shortcodes and if **you'll** change this value your old shortcodes will be broken"
    Should be "does not affect" and "you".
1. Same page: "define custom hotkey"
    Should be "define a custom hotkey"
1. CSS page: "You can overview the original styles to overwrite **it**"
    Should be "to overwrite **them**"
1. You can use **next** variables in your custom CSS
    Should be "the following".

I completely understand that this is a simple language issue and/or just typos. I'd be happy to change this text in the code here if I have access. It takes a while for pull requests to get processed.
l If there are more of these, where do you want them reported? For now I'll just add anything I find to this thread. Thanks!

**Comment by gndev** [comment]
Hey Tony,

thank you for corrections.

I hope these typos are fixed in new version (5.0.0), because it provides completely rewritten admin part. I've just published new version at GitHub and will publish it at wp.org in next monday/tuesday.
