### ISSUE TITLE
Add shortcode for gaiaGPS

### ISSUE THREAD

**Issue by supernovae** [gndev/shortcodes-ultimate#61]
Is it possible to add a shortcode to implement GaiGPS Maps? 

Their iframe setup is here:
https://blog.gaiagps.com/embedmaps/

**Comment by gndev** [comment]
Hi Byron,

I'm not sure that this is an enough popular service, to add it. You can easily add it using Shortcode Creator add-on. Or, you can add this shortcode using [API](http://docs.getshortcodes.com/article/45-how-to-add-custom-shortcodes).
