### ISSUE TITLE
posts() function in /inc/core/shortcodes.php needs $original_atts variable moved

### ISSUE THREAD

**Issue by lightwaymedia** [gndev/shortcodes-ultimate#62]
$original_attributes was being overwritten by after the call of the shortcode_atts function (at line 1202). This prevented multiple taxonomy queries (i.e., taxonomy_2) from being recognized later in $original_atts.

My recommendation: move $original_atts from line 1221 to 1202 (right before the call of shortcode_atts function)

**Comment by lightwaymedia** [comment]
Is there any information on this request? One of our bigger projects is reliant on Shortcodes and this issue seems worthy of resolving.

**Comment by gndev** [comment]
Hi Nick,

sorry for the delay in getting back to you.

I'll definitely look into this before closest update.

**Comment by gndev** [comment]
Hi Nick,

updated version (5.0.2) will be available in a few days at w.org.
