### ISSUE TITLE
Custom shortcode callback function is never called

### ISSUE THREAD

**Issue by carloscabo** [gndev/shortcodes-ultimate#67]
`WordPress 4.9.4 + Shortcodes Ultimate Version 5.0.3`  
I've followed the basic sample provided in the documentation to add a custom shortcode (https://docs.getshortcodes.com/article/45-how-to-add-custom-shortcodes).

Copied both parts ( definition and callback function ) into the `functions.php` of my theme.
 
First part seems to work fine (new shortcode definition), I can insert the shortcode from the WP admin with no problem, but the callback function is never called... so the HTML _rendering_ is never done... and I see the shortcode text in the page, not the HTML defined in the callback.

![image](https://user-images.githubusercontent.com/3063164/36369536-dcaff0dc-155b-11e8-89ba-d16e930197bd.png)

Could please confirm this issue or point me towards what is happening.
TIA!

**Comment by gndev** [comment]
Hi Carlos,

I've used incorrect parameter name in the documentation. Sorry.

Use `function` instead of `callback`.

Example:

```php
function register_my_custom_shortcode( $shortcodes ) {

	$shortcodes['heading2'] = array(
		'name' => __( 'Heading 2', 'textdomain' ),
		'type' => 'wrap',
		'function' => 'my_custom_shortcode',
	);

	return $shortcodes;

}
```

**Comment by carloscabo** [comment]
I've been trying this morning and works perfectly using `function`, I've seen that you updated the docs too. Perfect. **Thx a lot for the fast response.** This is done! 👍
