### ISSUE TITLE
Frame align center

### ISSUE THREAD

**Issue by josch87** [gndev/shortcodes-ultimate#71]
Frame is broken when aligned center.

Please see:
[su_frame align="center"]Content[/su_frame]

WordPress 4.9.4
Theme: Twenty Seventeen 1.4

**Comment by gndev** [comment]
Hi @josch87 ,

this shortcode is intended to use with images, not a text.

`[su_frame align="center"]<img src="https://example.com/image.jpg">[/su_frame]`
