### ISSUE TITLE
[Feature Request] Permalink: add options

### ISSUE THREAD

**Issue by josch87** [gndev/shortcodes-ultimate#72]
Add options to modify following attibutes for Permalink shortcode:

- [ ] title / Possible values: Any text value / Default value: currently same as content, please change to none

and maybe more attributes like
- [ ] download / id of an item in media gallery should be possible / Possible values: Yes, No / Default value: No

- [ ] rel / Possible values: alternate, author, bookmark, external, help, license, next, nofollow, noreferrer, noopener, prev, search, tag
...

Thank you

**Comment by gndev** [comment]
Added in 5.0.5
