### ISSUE TITLE
Nested su_spoilers are broken

### ISSUE THREAD

**Issue by bethwarsaw** [gndev/shortcodes-ultimate#77]
Our nested spoilers have been fine until the latest commit. While the nested spoilers are still visible, their contents do not collapse or expand with the spoiler.

**Comment by Rainbow-Brite** [comment]
Same issue here. For example, this used to work fine:

`[su_spoiler title="Announcements" style="fancy"]
[su_spoiler title="Original Cast Members on Broadway" open="yes"]
[_/su_spoiler]
[/su_spoiler]`

Now, to make the nested spoiler work at all, I have to change it to the following, with an extra underscore and quotation marks removed:

`[su_spoiler title="Announcements" style="fancy"]
[_su_spoiler title=Original Cast Members on Broadway open="yes"]
[_/su_spoiler]
[/su_spoiler]`

But then the nested spoiler only shows the first word of its title and is not automatically open as it used to be. So it looks like this:

Announcements
Original

All nested spoilers after "Original Cast Members on Broadway" display fine. But this has also broken the ability to use italics in nested spoiler titles with the em tag. Please roll back this update until this can be fixed. It has broken many, many pages on my website and there is no way to fix them.

**Comment by gndev** [comment]
Add the following code to your functions.php file:

`update_option( 'su_option_do_nested_shortcodes_alt', true, false );`

Then reinstall the plugin.
