### ISSUE TITLE
Content slider Broken after update to 5.0.4

### ISSUE THREAD

**Issue by chedmund** [gndev/shortcodes-ultimate#79]
First, the plugin is great, very helpful. I recently upgraded from 4.9.9 to 5.0.4 and after doing so all existing Content Sliders are broken. I tried creating a new one using the example:

[su_content_slider style=”default” effect=”slide” arrows=”yes” pages=”no” autoplay=”5″ class=””][su_content_slide] Slide content [/su_content_slide]
[su_content_slide] Slide content [/su_content_slide]
[su_content_slide] Slide content [/su_content_slide][/su_content_slider]

and that one does not work as well. Inspector gave me the following error:

TypeError: undefined is not an object (evaluating ‘$slider.data(‘owlCarousel’).autoHeight’)
(anonymous function) extra.js:204

hope that helps

**Comment by chedmund** [comment]
Did a little more troubleshooting and updated the plugin incrementally from 4.9.9 to 5.0.4. The content slider starts breaking after upgrading from 5.0.1 to 5.0.2.

**Comment by gndev** [comment]
Hello @chedmund,

you need to update the Extra shortcodes add-on to the latest version - 1.5.12.

Please contact me using [this page](https://getshortcodes.com/support/) if you do not have access to updates.
