### ISSUE TITLE
Allow Contributors to use shortcodes

### ISSUE THREAD

**Issue by nathan93** [gndev/shortcodes-ultimate#82]
Is there any way to allow users in the contributor role to use shortcodes? On my site, the Shortcodes Ultimate button does not appear on post editors for contributors. Thanks

**Comment by gndev** [comment]
Hello @nathan93,

you need to allow contributors to upload media files to enable the "Insert shortcode" button. I highly do not recommend doing this, because **this is insecure**.

If you still need this, add the following snippet to the `functions.php` file of your active theme:

```php
add_action( 'admin_init', 'allow_contributor_uploads' );

function allow_contributor_uploads() {

	if ( ! current_user_can( 'contributor' ) || current_user_can( 'upload_files' ) ) {
		return;
	}

	$contributor = get_role( 'contributor' );
	$contributor->add_cap( 'upload_files' );

}
```

There is other methods: https://wpbuffs.com/how-to-allow-contributors-to-upload-images-in-wordpress/

**Comment by nathan93** [comment]
Hello, I added this to the functions.php file, and it allows contributors to upload media now but it still doesn't show the Insert Shortcode button for contributors.

**Comment by vanokhin** [comment]
Hello @nathan93,

remove that code and add the following instead:

```php
/**
 * Required capability to access the 'Insert Shortcode' button.
 * User roles and custom capabilities are allowed.
 */
$su_generator_capability = 'edit_posts';

update_option( 'su_option_generator_access', $su_generator_capability, false );
```

**Comment by nathan93** [comment]
Hello, 

Doing this makes my site unable to load, it loads a blank white page after adding this code.

**Comment by vanokhin** [comment]
Hello @nathan93,

this code potentially could not trigger any errors. Please make sure you've inserted it in the right place. Please also check there is no extra dots, semicolons or anything else.

If you do not have enough coding experience, post your functions.php file code here.

**Comment by nathan93** [comment]
Hello, 

I mis-read your post. I tried inserting the code into wp-includes/functions.php instead of the functions.php in my current theme. Doing this worked. 

Thank you
