### ISSUE TITLE
Dispone de metadatos? 

### ISSUE THREAD

**Issue by TopCheff** [gndev/shortcodes-ultimate#87]
Hola, una pregunta dispone de metadatos shema.org? cada uno de los shortcode? Gracias!

**Comment by gndev** [comment]
Hi @TopCheff,

I do not speak Spanish.

**Comment by gndev** [comment]
If I get you right, you're asking about schema.org support. Currently, schema.org microdata isn't supported.

**Comment by TopCheff** [comment]
ok, thank you!
